/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as chatRouteRouteImport } from './routes/(chat)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as chatChatIndexRouteImport } from './routes/(chat)/chat/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as chatChatConversationIdRouteImport } from './routes/(chat)/chat/$conversationId'

const chatRouteRoute = chatRouteRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const chatChatIndexRoute = chatChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => chatRouteRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const chatChatConversationIdRoute = chatChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => chatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof chatRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/chat/$conversationId': typeof chatChatConversationIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/chat': typeof chatChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof chatRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/chat/$conversationId': typeof chatChatConversationIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/chat': typeof chatChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(chat)': typeof chatRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/(chat)/chat/$conversationId': typeof chatChatConversationIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/(chat)/chat/': typeof chatChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/chat/$conversationId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/chat/$conversationId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/(chat)'
    | '/demo/tanstack-query'
    | '/(chat)/chat/$conversationId'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/(chat)/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  chatRouteRoute: typeof chatRouteRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(chat)': {
      id: '/(chat)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)/chat/': {
      id: '/(chat)/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof chatChatIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)/chat/$conversationId': {
      id: '/(chat)/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof chatChatConversationIdRouteImport
      parentRoute: typeof chatRouteRoute
    }
  }
}

interface chatRouteRouteChildren {
  chatChatConversationIdRoute: typeof chatChatConversationIdRoute
  chatChatIndexRoute: typeof chatChatIndexRoute
}

const chatRouteRouteChildren: chatRouteRouteChildren = {
  chatChatConversationIdRoute: chatChatConversationIdRoute,
  chatChatIndexRoute: chatChatIndexRoute,
}

const chatRouteRouteWithChildren = chatRouteRoute._addFileChildren(
  chatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  chatRouteRoute: chatRouteRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
